### ISSUE TITLE
incorporate generic ref data loading from reference containers

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/template-snakemake#1]
The template should contain a snakemake module under `workflow/rules/commons/05_refcon.smk` that realizes the functionality to support loading reference data files from reference containers.

This should work roughly along the lines of the `refcon_load.smk` module in the reference container repository.

**Comment by svenwillger** [comment]
Modifications I did on the code to incorporate generic ref data:

- added the module `05_refcon.smk` to workflow/rules/commons/
- included a `reference_container.yaml` in the `config` folder with examples that should be included in the final config file
- in the module `01_constants` I added the location of the reference containers (as set through a config file)
https://github.com/core-unit-bioinformatics/template-snakemake/blob/ee5c29344b79b387a975bea6c3b7c6b9ed0a8c2c/workflow/rules/commons/01_constants.smk#L31

- in the module `05_refcon.smk` the following modifications were included:
     - removed the `REFCON_USE_RUN` parts and the `singularity` parts in the rules
      
     - to check if a reference container is used and if `True` where to find it:
https://github.com/core-unit-bioinformatics/template-snakemake/blob/ee5c29344b79b387a975bea6c3b7c6b9ed0a8c2c/workflow/rules/commons/05_refcon.smk#L20-L28

     - set the proper location for the reference file (line 77)
https://github.com/core-unit-bioinformatics/template-snakemake/blob/ee5c29344b79b387a975bea6c3b7c6b9ed0a8c2c/workflow/rules/commons/05_refcon.smk#L73-L83

**Comment by ptrebert** [comment]
Functionality merged into `dev` in d85f135f0948d77c78f3a59fa8ece59582888070
