### ISSUE TITLE
add basic testing functionality

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/template-snakemake#3]
@svenwillger 
as discussed via webex, implement a few rules in `snaketests.smk` that call (= test working state) all functions in the `pyutils` module. If appropriate, add a very simple reference container in the refcon repo that would results in a tiny reference container with some mock file to also test the functions related to refcon handling.

I created the `add-testing` branch for this functionality.

**Comment by svenwillger** [comment]
A workflow was created with rules that check functionality of the functions in `02_pyutils.smk`. 

New functions to get the username and the timestamp were added to `02_pyutils.smk`.

The rule "dump_config" from the branch `add-config_dump` was also added to this branch.

Folders and files that are required for the tests were added:
- the folder `test_folder` with the required files for the tests was added to the main folder 
- a `scripts` folder was added to `/workflow` with a test script
- "test_container.yaml" was added to config to point to the test container

The whole `/workflow` folder was checked and modified by `snakefmt` to standardize the code. 

The commit message is "add testing workflow with required files" and the hash is `b493662`.
