### ISSUE TITLE
Syntax error in commons rule 40_pyutils.smk

### ISSUE THREAD

**Issue by svenwillger** [core-unit-bioinformatics/template-snakemake#33]
In the code part posted below are two issues that needs to be addressed:

1. In L410 'warning_msg' needs to be replaced with 'error_msg' because that is what is defined in L405-409.
2. If the repo is not cloned from a git remote it will throw and en error since 'remotes' is not defined (see L413-414) and terminate the pipeline. 
    The question here is:
    - Do we want to be more specific on how to upload the repository through git onto HILBERT?
    - Just trigger a warning (without terminating the pipeline) and leave the git part empty in the run_config.yaml?  

https://github.com/core-unit-bioinformatics/template-snakemake/blob/3547b7cf451e00c50f168a8e5cbb0da9a5c91c50/workflow/rules/commons/40_pyutils.smk#L398-L414

**Comment by ptrebert** [comment]
Closed via #34
