### ISSUE TITLE
add rule to dump config

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/template-snakemake#4]
@svenwillger 
Add a rule in Snakefile (in snaketests as well) to dump the loaded configuration into a YAML file to under `results/run_config.yaml`.

Please add a timestamp and the ID of the user who executed the pipeline before dumping the file (try to protect these values in the config by adding, e.g., an underscore like `_timestamp` if allowed by YAML). See Python's `os` module to get the user name.

**Comment by svenwillger** [comment]
A rule was added in Snakemake (in snaketests.smk as well) that dumps the timestamp (as '_timestamp:') and the username (as '_username:') together with all config files (concatenated) into a YAML file in `results/run_config.yaml`.

Additionally, `snakefmt` was run on the complete `/workflow` folder to standardize the full code. 

The commit message is "addition of rule config_dump and run snakefmt" and the hash is `e263220`.

A pull request was sent.
